VirtoCommerce/vc-module-catalog-personalization

VirtoCommerce.CatalogPersonalizationModule.Core/Model/TaggedItemOutlineSyncProgressInfo.cs
VirtoCommerce.CatalogPersonalizationModule.Core/Model/TaggedItemOutlineSyncPushNotification.cs
VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
VirtoCommerce.CatalogPersonalizationModule.Web/BackgroundJobs/TaggedItemOutlinesSynchronizationJob.cs
VirtoCommerce.CatalogPersonalizationModule.Web/Controllers/Api/PersonalizationModuleController.cs
VirtoCommerce.CatalogPersonalizationModule.Web/Localizations/en.VirtoCommerce.CatalogPersonalization.json
VirtoCommerce.CatalogPersonalizationModule.Web/Model/TaggedItemOutlinesSynchronizationRequest.cs
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/outlines-synchronization-progress.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/outlines-synchronization-progress.tpl.html
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/catalog-personalization.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/resources/catalog-personalization-api.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/widgets/runOutlinesSynchronizationWidget.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/widgets/runOutlinesSynchronizationWidget.tpl.html
VirtoCommerce.CatalogPersonalizationModule.Web/VirtoCommerce.CatalogPersonalizationModule.Web.csproj

- Added API endpoint POST "api/personalization/outlines/synchronization" for manual sync;
- Added button to start sync to Personalization settings blade;

#21 Add a possibility to run Tagged items outline synchronization through UI by demand:

---

VirtoCommerce.CatalogPersonalizationModule.Data/Services/Policies/UpTreeTagPropagationPolicy.cs

Fixed bug when variations and hidden products were not counted in UpTree propagation policy;

#23: Fixed bug when variations and hidden products were not counted in UpTree propagation policy;

---

VirtoCommerce.CatalogPersonalizationModule.Core/Model/EffectiveTag.cs
VirtoCommerce.CatalogPersonalizationModule.Core/Model/Search/TaggedItemResponseGroup.cs
VirtoCommerce.CatalogPersonalizationModule.Core/Model/TaggedItem.cs
VirtoCommerce.CatalogPersonalizationModule.Core/Services/ITagPropagationPolicy.cs
VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
VirtoCommerce.CatalogPersonalizationModule.Data/Search/Indexing/TaggedItemDocumentBuilderBase.cs
VirtoCommerce.CatalogPersonalizationModule.Data/Services/PersonalizationService.cs
VirtoCommerce.CatalogPersonalizationModule.Data/Services/Policies/DownTreeTagPropagationPolicy.cs
VirtoCommerce.CatalogPersonalizationModule.Data/Services/Policies/TreeTagPropagationPolicy.cs
VirtoCommerce.CatalogPersonalizationModule.Data/Services/Policies/UpTreeTagPropagationPolicy.cs
VirtoCommerce.CatalogPersonalizationModule.Data/VirtoCommerce.CatalogPersonalizationModule.Data.csproj
VirtoCommerce.CatalogPersonalizationModule.Web/Controllers/Api/PersonalizationModuleController.cs
VirtoCommerce.CatalogPersonalizationModule.Web/Localizations/en.VirtoCommerce.CatalogPersonalization.json
VirtoCommerce.CatalogPersonalizationModule.Web/Localizations/ru.VirtoCommerce.CatalogPersonalization.json
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/tag-list.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/tag-list.tpl.html
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/widgets/tagsWidget.js
VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/widgets/tagsWidget.tpl.html

show tags total count with inherited tags
show inherited tags

vp-604_show_inherited_tags

---

src/VirtoCommerce.CatalogPersonalizationModule.Data/Repositories/PersonalizationRepository.cs

Fix error when synchronizing outline for up tree propagation

VP-1557 Error when synchronize outline for up tree propagation

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/ExportImport/PersonalizationExportImport.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/Module.cs

VP-2291: Rewrite export according to V3 pattern

---

VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3105

VP-3105: Fix logo

---

src/VirtoCommerce.CatalogPersonalizationModule.Data/Migrations/20200914134605_AddTaggedItemUniqueIndex.Designer.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Migrations/20200914134605_AddTaggedItemUniqueIndex.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Repositories/PersonalizationDbContext.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/Controllers/Api/PersonalizationModuleController.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/tag-list.js

Add unique index and handle error

VP-4690: Prevent tagged items duplication

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/tag-list.js

VP-6770: Replace panel action icons

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/tag-list.tpl.html

https://virtocommerce.atlassian.net/browse/PT-219
Fix Icon tag

PT-219:  Edit icon color is wrong in product tag selection blade

---

src/VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data/VirtoCommerce.CatalogPersonalizationModule.Data.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-207

PT-207: Enable Source link support

---

src/VirtoCommerce.CatalogPersonalizationModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/Localizations/en.VirtoCommerce.CatalogPersonalization.json
src/VirtoCommerce.CatalogPersonalizationModule.Web/Module.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/VirtoCommerce.CatalogPersonalizationModule.Web.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-2215

PT-2215: Apply job settings on-the-fly

---

docs/index.md

PT-2637 fix broken image links

---

src/VirtoCommerce.CatalogPersonalizationModule.Data/Search/CategorySearchUserGroupsRequestBuilder.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Search/ProductSearchUserGroupsRequestBuilder.cs
tests/VirtoCommerce.CatalogPersonalizationModule.Test/Indexations/CategorySearchUserGroupsRequestBuilderTests.cs
tests/VirtoCommerce.CatalogPersonalizationModule.Test/Indexations/ProductSearchUserGroupsRequestBuilderTests.cs

PT-5038: Fix user group in search criteria

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
src/VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data/Repositories/PersonalizationDbContext.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/VirtoCommerce.CatalogPersonalizationModule.Data.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/VirtoCommerce.CatalogPersonalizationModule.Web.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest
tests/VirtoCommerce.CatalogPersonalizationModule.Test/VirtoCommerce.CatalogPersonalizationModule.Test.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/Module.cs

https://virtocommerce.atlassian.net/browse/PT-7292

PT-7292: Remove redundant BuildServiceProvider from the module startup

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/Scripts/blades/outlines-synchronization-progress.js

Fix synchronize outlines icon display
https://virtocommerce.atlassian.net/browse/PT-7466

PT-7466: Fix synchronize outlines icon display

---

src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/Migrations/20230111170149_Initial.Designer.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/Migrations/20230111170149_Initial.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/Migrations/PersonalizationDbContextModelSnapshot.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/TaggedItemOutlineEntityConfiguration.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/VirtoCommerce.CatalogPersonalizationModule.Data.MySql.csproj

fix: Index limitation on MySql
https://virtocommerce.atlassian.net/browse/PT-10029

PT-10029: Index limitation on MySql

---

src/VirtoCommerce.CatalogPersonalizationModule.Web/package-lock.json
src/VirtoCommerce.CatalogPersonalizationModule.Web/package.json
src/VirtoCommerce.CatalogPersonalizationModule.Web/webpack.config.js

feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395

PT-9395: add nodejs-lts support

---

.editorconfig
Directory.Build.props
VirtoCommerce.CatalogPersonalizationModule.sln.DotSettings
module.ignore
src/VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/VirtoCommerce.CatalogPersonalizationModule.Data.MySql.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.PostgreSql/VirtoCommerce.CatalogPersonalizationModule.Data.PostgreSql.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.SqlServer/VirtoCommerce.CatalogPersonalizationModule.Data.SqlServer.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data/Repositories/PersonalizationRepository.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Search/Indexing/TaggedItemDocumentBuilderBase.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Services/CategoryTaggedEntitiesService.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Services/ProductTaggedEntitiesService.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/VirtoCommerce.CatalogPersonalizationModule.Data.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/Controllers/Api/PersonalizationModuleController.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/ExportImport/PersonalizationExportImport.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/Module.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/VirtoCommerce.CatalogPersonalizationModule.Web.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest
tests/VirtoCommerce.CatalogPersonalizationModule.Test/VirtoCommerce.CatalogPersonalizationModule.Test.csproj

https://virtocommerce.atlassian.net/browse/PT-10449

PT-10449: Use updated Crud and Search services

---

Directory.Build.props
src/VirtoCommerce.CatalogPersonalizationModule.Core/VirtoCommerce.CatalogPersonalizationModule.Core.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.MySql/VirtoCommerce.CatalogPersonalizationModule.Data.MySql.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.PostgreSql/VirtoCommerce.CatalogPersonalizationModule.Data.PostgreSql.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data.SqlServer/VirtoCommerce.CatalogPersonalizationModule.Data.SqlServer.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Data/Repositories/PersonalizationDbContext.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/VirtoCommerce.CatalogPersonalizationModule.Data.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/VirtoCommerce.CatalogPersonalizationModule.Web.csproj
src/VirtoCommerce.CatalogPersonalizationModule.Web/module.manifest
src/VirtoCommerce.CatalogPersonalizationModule.Web/package-lock.json
tests/VirtoCommerce.CatalogPersonalizationModule.Test/VirtoCommerce.CatalogPersonalizationModule.Test.csproj

https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogPersonalization_3.800.0-pr-74-c465.zip

PT-14740: .net 8

---

src/VirtoCommerce.CatalogPersonalizationModule.Core/Events/TaggedItemChangedEvent.cs
src/VirtoCommerce.CatalogPersonalizationModule.Core/Events/TaggedItemChangingEvent.cs
src/VirtoCommerce.CatalogPersonalizationModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Handlers/LogChangesChangedEventHandler.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Handlers/TaggedItemChangedEventHandler.cs
src/VirtoCommerce.CatalogPersonalizationModule.Data/Services/PersonalizationService.cs
src/VirtoCommerce.CatalogPersonalizationModule.Web/Localizations/en.VirtoCommerce.CatalogPersonalization.json
src/VirtoCommerce.CatalogPersonalizationModule.Web/Module.cs

Added indexation switchers for event based and operation changed log indexation (disabled by default):
https://virtocommerce.atlassian.net/browse/VCST-3630
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogPersonalization_3.806.0-pr-81-9036.zip

VCST-3630: Track change Tagged Item

---

src/VirtoCommerce.CatalogPersonalizationModule.Data/Search/Indexing/TaggedItemIndexChangesProvider.cs

https://virtocommerce.atlassian.net/browse/VCST-3833
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogPersonalization_3.807.0-pr-83-e43f.zip

VCST-3833: Correct log ObjectType for TaggedItem changes provider
